/* DO NOT EDIT THIS FILE - it is machine generated */
#include "automationapi_Session.h"
#include "..\Core\Core.h"
#include "..\AppPartOps\PartOps.h"
#include "..\AppPartOps\Journaling_Session.h"
/* Header for class automationapi_Session */



extern  void Session_initSession()
{
	initializeProduct();
}

extern  int Session_MakePart(char**& inputParams)
{
	char* c = *inputParams;

	std::string partFilePath = std::string(c);

	Application::PartFile* partFile = Journaling_Session_MakePart(partFilePath);

	int guid = partFile->GetGuid();

	return guid;

}

